# Generated by Django 3.2.22 on 2023-10-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
