# Generated by Django 4.2.7 on 2023-11-03 21:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_review_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=90, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
